const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const data = JSON.parse(fs.readFileSync(path.join(root, 'lesson.json'), 'utf8'));
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const source = id => data.sources.find(s => s.id === id);
const promptText = p => `${p.body}\n\n${data.commonGuard}`;
const mdTable = t => [t.headers.join(' | '), t.headers.map(() => '---').join(' | '), ...t.rows.map(r => r.join(' | '))].map(s => `| ${s} |`).join('\n');
const htmlTable = t => `<div class="table-wrap"><table><thead><tr>${t.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const sourceHtml = ids => `<p class="sources">操作依據：${ids.map(id=>{const s=source(id);return `<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`;}).join(' · ')}</p>`;
function figure(file) {
  const shot=data.screenshots.find(s=>s.file===file);
  return `<figure class="screenshot"><button class="image-open" type="button" data-image="screenshots/${esc(file)}" data-caption="${esc(shot.title+'｜'+shot.kind)}" aria-label="放大截圖：${esc(shot.title)}"><img src="screenshots/${esc(file)}" alt="${esc(shot.title+'；'+shot.kind)}" loading="eager"><span>點圖放大</span></button><figcaption><strong>${esc(shot.title)}</strong><span>${esc(shot.kind)} · 2026/10/2 擷取</span><p>${esc(shot.caption)}</p><a href="${esc(source(shot.source).url)}" target="_blank" rel="noopener noreferrer">查看原始來源</a></figcaption></figure>`;
}
function stepHtml(s,i) {
  return `<article class="step"><div class="step-heading"><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(s.title)}</h3></div><div class="step-body"><h4>你要做</h4><ol>${s.actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ol><div class="step-checks"><p><strong>你會看到</strong>${esc(s.see)}</p><p><strong>如果畫面不一樣</strong>${esc(s.different)}</p><p><strong>完成標準</strong>${esc(s.done)}</p></div></div></article>`;
}
function chapterHtml(c) {
  return `<section id="${c.id}" class="chapter"><details ${c.number==='00'||c.number==='01'?'open':''}><summary><span class="chapter-no">${c.number}</span><h2>${esc(c.title)}</h2><span class="chapter-toggle" aria-hidden="true">＋</span></summary><div class="chapter-body"><p class="lead">${esc(c.lead)}</p>${c.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${c.table?htmlTable(c.table):''}${c.steps?`<div class="steps">${c.steps.map(stepHtml).join('')}</div>`:''}${c.promptIds?`<div class="related-prompts"><span>這一段可以用</span>${c.promptIds.map(id=>{const p=data.prompts.find(p=>p.id===id);return `<a href="#prompt-${id}" data-prompt-link="${id}">${id} ${esc(p.title)}</a>`;}).join('')}</div>`:''}${c.image?figure(c.image):''}${c.image2?figure(c.image2):''}<div class="chapter-takeaway"><div><h3>老師先記這一句就好</h3><p>${esc(c.recall)}</p></div><div><h3>馬上試試看</h3><p>${esc(c.exercise)}</p></div><div><h3>如果卡住了</h3><ul>${c.troubles.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><div><h3>完成確認</h3><p>${esc(c.done)}</p></div></div>${c.sources?sourceHtml(c.sources):''}</div></details></section>`;
}
function promptHtml(p) {
  return `<article class="prompt-card" id="prompt-${p.id}" data-category="${esc(p.category)}" data-search="${esc([p.title,p.category,p.need,p.body].join(' '))}"><details><summary><span class="prompt-id">${p.id}</span><div><small>${esc(p.category)}</small><h3>${esc(p.title)}</h3></div><span aria-hidden="true">＋</span></summary><div class="prompt-content"><dl><div><dt>準備</dt><dd>${esc(p.need)}</dd></div><div><dt>用在哪裡</dt><dd>${esc(p.use)}</dd></div></dl><pre id="text-${p.id}">${esc(promptText(p))}</pre><button class="button copy" type="button" data-copy="text-${p.id}">複製這段提示詞</button><div class="followup"><strong>做出第一版，再接這句</strong><p>${esc(p.follow)}</p><strong>老師最後看這裡</strong><p>${esc(p.check)}</p></div></div></details></article>`;
}
function demoHtml() {
  const d=data.liveDemo;
  return `<section class="section-block live-demo" id="spark-demo"><p class="eyebrow">本次實作 · 2026/10/2 · 真實操作與成品</p><h2>${esc(d.title)}</h2><p>${esc(d.intro)}</p><p class="demo-context">${esc(d.context)}</p><div class="demo-stages">${d.stages.map(s=>`<article class="demo-stage"><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>${figure(s.image)}</article>`).join('')}</div><details class="demo-prompt"><summary>打開這次真正送出的完整提示詞</summary><pre id="demo-prompt-text">${esc(d.prompt)}</pre><button class="button copy" type="button" data-copy="demo-prompt-text">複製這次實作提示詞</button></details><div class="demo-review"><h3>${esc(d.reviewTitle)}</h3><p>${esc(d.review)}</p><details class="demo-prompt"><summary>看怎麼向 Spark 指出問題</summary><pre id="demo-revision-text">${esc(d.revisionPrompt)}</pre><button class="button copy" type="button" data-copy="demo-revision-text">複製精準修改要求</button></details>${d.revisionResult?`<p class="demo-result">${esc(d.revisionResult)}</p>`:''}${d.revisionImage?figure(d.revisionImage):''}</div><div class="demo-download"><a class="button primary" href="${esc(d.file)}" download>${esc(d.fileLabel)}</a>${d.revisionFile?`<a class="button secondary" href="${esc(d.revisionFile)}" download>下載 Spark 修正版（Word）</a>`:''}<p>${esc(d.fileNote)}</p></div><div class="chapter-takeaway"><div><h3>老師先記這一句就好</h3><p>${esc(d.recall)}</p></div><div><h3>馬上試試看</h3><p>${esc(d.exercise)}</p></div><div><h3>如果卡住了</h3><ul>${d.troubles.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><div><h3>完成確認</h3><p>${esc(d.done)}</p></div></div></section>`;
}
const categories=[...new Set(data.prompts.map(p=>p.category))];
const html=`<!doctype html>
<html lang="zh-Hant">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Gemini Spark 與族語老師的日常應用：三小時講義、本次真實任務與成品截圖、${data.prompts.length} 段可複製提示詞，實作備課包、任務、技能與排程。"><meta name="theme-color" content="#147d7e"><meta property="og:title" content="${esc(data.subtitle)}｜北市府第 4 堂"><meta property="og:type" content="website"><meta property="og:url" content="https://calumai.com/class/taipei-ai/2026-1002-gemini-assistant/"><title>${esc(data.subtitle)}｜北市府 AI 教學應用第 4 堂</title><link rel="icon" href="/assets/calumai-logo-mark.png"><link rel="stylesheet" href="styles.css?v=20261002b"><script src="lesson.js?v=20261002b" defer></script></head>
<body><a class="skip-link" href="#main">跳到講義內容</a>
<header class="site-header"><div class="shell header-inner"><a class="brand" href="../">CALUMAI <span>/ CLASS</span></a><nav aria-label="課程導覽"><a href="#basics">Gemini 日常</a><a href="#spark-demo">Spark 實作</a><a href="#prompts">提示詞庫</a><a href="#checklist">成果確認</a></nav></div></header>
<main id="main"><section class="intro shell"><p class="eyebrow">臺北市政府 AI 教學應用 · 第 4 堂 · 10/2 19:00–22:00</p><h1>${esc(data.title)}</h1><p class="subtitle">${esc(data.subtitle)}</p><p class="intro-copy">${esc(data.intro)}</p><div class="intro-actions"><a class="button primary" href="#spark-demo">看 Spark 實作與成品</a><a class="button secondary" href="#basics">開始第一個練習</a><a class="button secondary" href="gemini-spark-handout-pack.zip" download>下載講義與截圖</a><button class="button quiet" type="button" data-print>列印講義</button></div><p class="download-note">離線包包含講義、截圖與本次實作 Word 成品，請一起解壓縮保存。也可<a href="gemini-spark-handout.md" download>只下載 Markdown 文字版</a>。</p></section>
<section class="route-band"><div class="shell route-grid"><a href="#practice"><span>01 用自己的教材</span><h2>完成一份備課包</h2><p>流程、學習單與通知，一次整理。</p></a><a href="#spark-demo"><span>02 把工作接起來</span><h2>看一個真的完成的任務</h2><p>貼要求、開成品，再請 AI 修改。</p></a><a href="#skill"><span>03 下次再用</span><h2>存好規則與排程</h2><p>不必每次重講，也知道怎麼停止。</p></a></div></section>
<div class="shell lesson-layout"><aside class="toc" aria-label="章節目錄"><p>今天這樣做</p><a class="toc-demo" href="#spark-demo">先看 Spark 實作與成品</a><ol>${data.chapters.map(c=>`<li><a href="#${c.id}"><span>${c.number}</span>${esc(c.title)}</a></li>`).join('')}</ol><a class="toc-bank" href="#prompts">${data.prompts.length} 段提示詞</a><small>操作資料核對：2026/10/2<br>實際功能依自己的帳號而定。</small></aside><div class="lesson-body">
<section class="account-note"><strong>沒有 Spark，也能跟著做。</strong><p>Spark 目前需個人帳號、年滿 18 歲、Google AI Pro 或 Ultra 訂閱及活動記錄。一般 Gemini 路線仍可完成主要備課包；技能與排程依帳號是否開放使用。<a href="${source('spark').url}" target="_blank" rel="noopener noreferrer">查看 Google 官方條件</a></p></section>
${demoHtml()}
${data.chapters.map(chapterHtml).join('\n')}
<section class="section-block" id="prompt-builder"><p class="eyebrow">把範例換成自己的班級</p><h2>組一段自己的備課要求</h2><p>填入這五項，產生的是可以複製到 Gemini 的提示詞。本頁不會傳送教材給 AI。</p><form id="builder"><div class="form-grid"><label>給誰上課<input name="audience" required placeholder="例如：12 位國小三年級初學者"></label><label>這次主題<input name="topic" required placeholder="例如：問候語"></label><label>課程時間<input name="duration" required placeholder="例如：40 分鐘"></label><label>想拿到什麼<select name="result"><option>教學流程、學習單與答案、課前通知</option><option>10 分鐘不插電活動</option><option>分成三種程度的練習</option><option>只整理詞表，不新增活動</option></select></label></div><label>老師已核對的教材<textarea name="material" rows="5" required placeholder="貼上自己的族語、中文意思與來源。資料留在這個頁面，不會自動上傳。"></textarea></label><button class="button primary" type="submit">產生我的提示詞</button></form><div id="builder-result" hidden><pre id="builder-text"></pre><button class="button copy" type="button" data-copy="builder-text">複製我的提示詞</button></div></section>
<section class="section-block" id="prompts"><p class="eyebrow">想用哪一件，就打開哪一件</p><h2>族語老師的 ${data.prompts.length} 段提示詞</h2><p>每段都有素材、使用方式、第一版之後的修改句，以及老師要確認的地方。複製前把【括號】改成自己的資料。</p><div class="prompt-toolbar"><label class="search-label">找案例<input type="search" id="prompt-search" placeholder="搜尋詞表、家長、長輩、排程…"></label><div class="filters" role="group" aria-label="提示詞分類"><button type="button" data-filter="all" aria-pressed="true">全部</button>${categories.map(c=>`<button type="button" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div><p id="prompt-count" role="status">顯示 ${data.prompts.length} 段</p></div><div class="prompt-grid">${data.prompts.map(promptHtml).join('')}</div><p id="no-prompts" hidden>找不到符合的案例，換個關鍵字或按「全部」。</p></section>
<section class="section-block" id="screenshots"><p class="eyebrow">補充參考 · 與本次實作分開看</p><h2>Google 公開的產品示範</h2><p>本次自己的操作與成品在上方「真的跑一次」。下方兩張來自 Google 公開示範影片，不是我們的任務成果；各章附的官方說明頁則用來核對操作規則。</p>${figure('01-spark-official-demo.jpg')}${figure('09-gemini-official-interface.jpg')}</section>
<section class="section-block" id="checklist"><p class="eyebrow">檔案打得開，內容也核對過</p><h2>今天的成果確認</h2><p id="check-count" class="check-count" aria-live="polite">0 / ${data.checklist.length} 項完成</p><div class="checklist">${data.checklist.map((c,i)=>`<label><input type="checkbox" id="check-${i}"><span>${esc(c)}</span></label>`).join('')}</div><p class="local-note">勾選只留在目前畫面，不會上傳或替你建立 Spark 任務。</p></section>
<section class="section-block" id="faq"><h2>遇到問題，先看這裡</h2><div class="faq">${data.faqs.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</div></section>
<section class="section-block reference-block" id="references"><h2>官方操作依據</h2><p>功能與帳號條件核對於 2026/10/2；各章的族語教學案例為本課程自行設計。</p><ul>${data.sources.map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></li>`).join('')}</ul></section>
</div></div></main><footer class="shell"><a href="../">回到四堂課</a><span>CALUMAI / 族語老師的 AI 教學日常</span><a href="../2026-0918-gamified-learning/">回到第三堂</a></footer><div id="copy-status" role="status" aria-live="polite"></div><dialog id="image-dialog"><button type="button" class="dialog-close" aria-label="關閉放大截圖">關閉</button><h2 id="image-caption"></h2><img id="image-full" alt=""></dialog></body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);

const md=[`# ${data.title}`,`\n${data.subtitle}\n\n2026/10/2｜19:00–22:00｜三小時\n\n${data.intro}`,'## 完整章節架構',...data.chapters.map(c=>`- Chapter ${c.number}｜${c.title}（${c.minutes} 分鐘）`),'\n## 課程目標',...data.goals.map(g=>`- ${g}`),'\n## 課程流程與每章時間',mdTable({headers:['時間','分鐘','實作內容'],rows:data.timeline.map(t=>[t.time,String(t.minutes),t.name])}),'\n課程共 180 分鐘，包含 10 分鐘休息。提示詞庫供選用，不需要逐段教完；先完成一份備課包，再練一個任務、固定規則與排程。','\n## 今天完成的成果',...data.outcomes.map(o=>`- ${o}`),'\n## 先確認使用路線','\nGemini Spark 的帳號条件與功能以 [Google 官方說明]('+source('spark').url+') 為準。沒有 Spark 的學員使用一般 Gemini 對話、手動貼固定規則與行事曆提醒；這是替代路線，不算已建立 Spark 排程。'];
const demo=data.liveDemo;
md.push(`\n## ${demo.title}\n\n${demo.intro}\n\n${demo.context}`);
for(const s of demo.stages){const shot=data.screenshots.find(i=>i.file===s.image);md.push(`\n### ${s.title}\n\n${s.text}\n\n![${shot.title}](screenshots/${shot.file})\n\n${shot.kind}。${shot.caption}`);}
md.push(`\n### 這次真正送出的完整提示詞\n\n\`\`\`text\n${demo.prompt}\n\`\`\``,`\n### ${demo.reviewTitle}\n\n${demo.review}\n\n\`\`\`text\n${demo.revisionPrompt}\n\`\`\``);
if(demo.revisionResult)md.push('\n'+demo.revisionResult);
if(demo.revisionImage){const s=data.screenshots.find(s=>s.file===demo.revisionImage);md.push(`\n![${s.title}](screenshots/${s.file})\n\n${s.caption}`);}
md.push(`\n[${demo.fileLabel}](${demo.file})`,demo.revisionFile?`\n[下載 Spark 修正版（Word）](${demo.revisionFile})`:'',`\n${demo.fileNote}\n\n### 老師先記這一句就好\n\n${demo.recall}\n\n### 馬上試試看\n\n${demo.exercise}\n\n### 如果卡住了\n`,...demo.troubles.map(t=>`- ${t}`),`\n### 完成確認\n\n${demo.done}`);
for (const c of data.chapters) {
  md.push(`\n## Chapter ${c.number}｜${c.title}`,`\n預估 ${c.minutes} 分鐘\n\n${c.lead}`,...c.paragraphs.map(p=>'\n'+p));
  if(c.table)md.push('\n'+mdTable(c.table));
  if(c.steps)c.steps.forEach((s,i)=>md.push(`\n### Step ${i+1}｜${s.title}\n\n你要做：\n`,...s.actions.map((a,j)=>`${j+1}. ${a}`),`\n你會看到：\n\n${s.see}\n\n如果畫面不一樣：\n\n${s.different}\n\n完成標準：\n\n${s.done}`));
  if(c.promptIds)md.push('\n### 這一章可用的提示詞\n',...c.promptIds.map(id=>{const p=data.prompts.find(p=>p.id===id);return `- ${id} ${p.title}（見下方完整提示詞庫）`;}));
  for(const file of [c.image,c.image2].filter(Boolean)) {const s=data.screenshots.find(s=>s.file===file);md.push(`\n![${s.title}](screenshots/${file})\n\n${s.kind}，2026/10/2 擷取。${s.caption}\n\n[原始來源](${source(s.source).url})`);}
  md.push(`\n### 老師先記這一句就好\n\n${c.recall}\n\n### 馬上試試看\n\n${c.exercise}\n\n### 如果卡住了\n`,...c.troubles.map(t=>`- ${t}`),`\n### 完成確認\n\n${c.done}`);
  if(c.sources)md.push('\n操作依據：'+c.sources.map(id=>{const s=source(id);return `[${s.title}](${s.url})`;}).join('、'));
}
md.push('\n## 完整提示詞庫','\n每段先填【括號】內的資訊；「修改句」是第一次回覆後再送出的要求。所有練習都是草稿，不能取代族語老師核對。');
for(const p of data.prompts)md.push(`\n### ${p.id}｜${p.title}\n\n分類：${p.category}\n\n準備：${p.need}\n\n使用方式：${p.use}\n\n\`\`\`text\n${promptText(p)}\n\`\`\`\n\n第一版之後再接這句：\n\n> ${p.follow}\n\n老師最後核對：${p.check}`);
md.push('\n## 講師課前準備',...data.preparation.teacher.map(t=>`- ${t}`),'\n## 學員帳號與素材',...data.preparation.learner.map(t=>`- ${t}`),'\n## 常見問題與排錯');
for(const f of data.faqs)md.push(`\n### ${f.q}\n\n${f.a}`);
md.push('\n## 課後成果檢查表',...data.checklist.map(c=>`- [ ] ${c}`),'\n## 真實截圖清單與來源',`\n本講義共使用 ${data.screenshots.length} 張真實截圖。本課程實作圖片来自本次新任務與新成品；Google 公開示範與官方說明頁另外標明。沒有生成圖片冒充介面，也沒有把官方畫面說成本次任務成果。`.replace('来自','來自'));
for(const s of data.screenshots)md.push(`\n### ${s.title}\n\n![${s.title}](screenshots/${s.file})\n\n種類：${s.kind}\n\n${s.caption}\n\n[原始來源](${source(s.source).url})`);
md.push('\n## 資料核對與引用',...data.sources.map(s=>`- [${s.title}](${s.url})`),'\n功能資料核對日期：2026/10/2。族語教學情境、練習與提示詞為本課程自行設計。');
fs.writeFileSync(path.join(root,'gemini-spark-handout.md'),md.join('\n').replaceAll('帳號条件','帳號條件'));
console.log(`Built ${data.chapters.length} chapters, ${data.prompts.length} prompts, ${data.screenshots.length} screenshots; ${data.timeline.reduce((n,t)=>n+t.minutes,0)} minutes.`);
