const API="https://classroom-patrol.islanduni.chatgpt.site/api/patrol";
const entry=document.querySelector("#entry"),teacher=document.querySelector("#teacher"),student=document.querySelector("#student"),grid=document.querySelector("#student-grid");
let activeFilter="all",students=[],stream=null,snapshotTimer=null,pollTimer=null;
let teacherSession=JSON.parse(sessionStorage.getItem("patrolTeacher")||"null");
let studentSession=JSON.parse(sessionStorage.getItem("patrolStudent")||"null");
function show(view){[entry,teacher,student].forEach(el=>el.hidden=true);view.hidden=false;scrollTo(0,0)}
function message(selector,text,error=false){const el=document.querySelector(selector);el.textContent=text;el.classList.toggle("error",error)}
async function api(path,options={}){const response=await fetch(API+path,options);let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||"連線失敗，請稍後再試。");return body}
function tokenHeaders(token,json=true){return {Authorization:`Bearer ${token}`,...(json?{"Content-Type":"application/json"}:{})}}

document.querySelectorAll("[data-role]").forEach(button=>button.addEventListener("click",()=>{if(button.dataset.role==="teacher"){show(teacher);if(teacherSession)startTeacher()}else{show(student);const code=new URLSearchParams(location.search).get("code");if(code)document.querySelector("#join-code").value=code;if(studentSession)restoreStudent()}}));
document.querySelectorAll(".exit").forEach(button=>button.addEventListener("click",()=>{stopSharing();clearInterval(pollTimer);show(entry)}));

document.querySelector("#create-class").addEventListener("click",async event=>{event.currentTarget.disabled=true;message("#teacher-message","正在建立課堂…");try{teacherSession=await api("/classrooms",{method:"POST"});sessionStorage.setItem("patrolTeacher",JSON.stringify(teacherSession));startTeacher()}catch(error){message("#teacher-message",error.message,true);event.currentTarget.disabled=false}});
function startTeacher(){document.querySelector("#class-code").textContent=teacherSession.code.replace(/(\d{3})(\d{3})/,"$1 $2");document.querySelector("#copy-code").disabled=false;document.querySelector("#create-class").textContent="重新建立課堂";document.querySelector("#create-class").disabled=false;message("#teacher-message","課堂已建立，等待學生加入。");loadState();clearInterval(pollTimer);pollTimer=setInterval(loadState,5000)}
async function loadState(){if(!teacherSession)return;try{const state=await api(`/state?code=${teacherSession.code}`,{headers:tokenHeaders(teacherSession.teacherToken,false)});students=state.students.map(s=>({...s,status:s.helpRequested?"help":s.snapshotUpdatedAt?(s.online?"sharing":"offline"):"waiting"}));updateStats();render()}catch(error){message("#teacher-message",error.message,true)}}
function updateStats(){const sharing=students.filter(s=>s.status==="sharing"||s.status==="help").length,help=students.filter(s=>s.helpRequested).length,waiting=students.filter(s=>s.status==="waiting").length;document.querySelector("#stat-all").textContent=students.length;document.querySelector("#stat-sharing").textContent=sharing;document.querySelector("#stat-help").textContent=help;document.querySelector("#stat-waiting").textContent=waiting;document.querySelector("#student-count").textContent=students.length?`目前共 ${students.length} 位學生`:"目前沒有學生加入"}
function statusText(status){return status==="help"?"需要協助":status==="waiting"?"尚未分享":status==="offline"?"已離線":"分享中"}
function safe(value){return String(value).replace(/[<>&\"]/g,"")}
function imagePath(s){return `/image?code=${teacherSession.code}&studentId=${encodeURIComponent(s.id)}&v=${s.snapshotUpdatedAt}`}
async function loadImage(studentId,img){try{const s=students.find(x=>x.id===studentId),response=await fetch(API+imagePath(s),{headers:tokenHeaders(teacherSession.teacherToken,false)});if(!response.ok)return;const blob=await response.blob();if(img.src.startsWith("blob:"))URL.revokeObjectURL(img.src);img.src=URL.createObjectURL(blob)}catch{}}
function render(){const q=document.querySelector("#student-search").value.trim();const list=students.filter(s=>(activeFilter==="all"||s.status===activeFilter)&&s.name.includes(q));grid.innerHTML=list.map(s=>`<button class="student-card ${s.status}" data-id="${s.id}"><div class="screen">${s.snapshotUpdatedAt?`<img alt="${safe(s.name)}的最新畫面">`:""}<span class="status">${statusText(s.status)}</span></div><div class="student-info"><span class="avatar">${safe(s.name.slice(-1))}</span><span><b>${safe(s.name)}</b><small>${s.snapshotUpdatedAt?new Date(s.snapshotUpdatedAt).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"等待分享"}</small></span></div></button>`).join("");grid.querySelectorAll(".student-card").forEach(card=>{const img=card.querySelector("img");if(img)loadImage(card.dataset.id,img);card.addEventListener("click",()=>{const s=students.find(x=>x.id===card.dataset.id),dialogImage=document.querySelector("#dialog-image");document.querySelector("#dialog-name").textContent=s.name;dialogImage.removeAttribute("src");if(s.snapshotUpdatedAt)loadImage(s.id,dialogImage);document.querySelector("#student-dialog").showModal()})})}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter===activeFilter));render()}));
document.querySelector("#student-search").addEventListener("input",render);
document.querySelector("#copy-code").addEventListener("click",async event=>{const link=`${location.origin}/class/patrol/?code=${teacherSession.code}`;await navigator.clipboard.writeText(link);event.currentTarget.textContent="已複製";setTimeout(()=>event.currentTarget.textContent="複製邀請連結",1200)});

document.querySelector("#join-button").addEventListener("click",async event=>{const code=document.querySelector("#join-code").value.replace(/\D/g,"");const name=document.querySelector("#student-name").value.trim();event.currentTarget.disabled=true;message("#student-message","正在加入課堂…");try{const joined=await api("/join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,name})});studentSession={...joined,code};sessionStorage.setItem("patrolStudent",JSON.stringify(studentSession));restoreStudent()}catch(error){message("#student-message",error.message,true);event.currentTarget.disabled=false}});
function restoreStudent(){document.querySelector("#join-code").value=studentSession.code;document.querySelector("#student-name").value=studentSession.name;document.querySelector("#join-code").disabled=true;document.querySelector("#student-name").disabled=true;document.querySelector("#join-button").hidden=true;document.querySelector("#share-area").hidden=false;message("#student-message",`${studentSession.name}，你已加入課堂 ${studentSession.code}。`)}

const shareButton=document.querySelector("#share-button"),video=document.querySelector("#share-video"),shareSuccess=document.querySelector("#share-success");
function setShareState(isSharing){video.hidden=!isSharing;shareSuccess.hidden=!isSharing;shareButton.textContent=isSharing?"停止分享":"開始分享畫面"}
function stopSharing(){clearInterval(snapshotTimer);snapshotTimer=null;if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;video.srcObject=null;setShareState(false)}
async function sendSnapshot(){if(!stream||!studentSession||video.readyState<2)return;const canvas=document.createElement("canvas"),scale=Math.min(1,640/video.videoWidth);canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.55));if(!blob)return;try{await api(`/snapshot?code=${studentSession.code}&studentId=${encodeURIComponent(studentSession.studentId)}`,{method:"POST",headers:tokenHeaders(studentSession.studentToken,false),body:blob})}catch(error){message("#student-message",error.message,true)}}
shareButton.addEventListener("click",async()=>{if(stream){stopSharing();return}try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:2},audio:false});video.srcObject=stream;await video.play();setShareState(true);await sendSnapshot();snapshotTimer=setInterval(sendSnapshot,10000);stream.getVideoTracks()[0].addEventListener("ended",stopSharing,{once:true})}catch(error){if(error.name!=="NotAllowedError")message("#student-message","無法開始分享，請確認瀏覽器允許螢幕分享。",true)}});
document.querySelector("#help-button").addEventListener("click",async event=>{const requested=!event.currentTarget.classList.contains("active");try{await api("/help",{method:"POST",headers:tokenHeaders(studentSession.studentToken),body:JSON.stringify({code:studentSession.code,studentId:studentSession.studentId,requested})});event.currentTarget.classList.toggle("active",requested);event.currentTarget.textContent=requested?"已通知老師，請稍候":"舉手｜我需要老師協助"}catch(error){message("#student-message",error.message,true)}});
document.querySelector("#announce").addEventListener("click",()=>document.querySelector("#notice-dialog").showModal());
document.querySelectorAll(".dialog-close").forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));
