const names=["陳品妤","林子晴","張雅婷","黃靖恩","吳佳蓉","李承翰","王思涵","高于翔","江語晨","田家豪","葉芷晴","周冠宇","郭沛珊","何雨潔","羅致遠","許孟庭","楊子維","鍾佩芸","潘柏安","徐欣怡","簡書妍","戴宇恩","宋庭瑄","洪凱翔","鄭宜蓁"];
const students=names.map((name,i)=>({name,group:`第 ${Math.floor(i/6)+1} 組`,status:i===1||i===9||i===16?"help":i===6||i===18?"waiting":i===22?"offline":"sharing",updated:i===22?"3 分鐘前":`${i%9+2} 秒前`,scene:i%4}));
const entry=document.querySelector("#entry"),teacher=document.querySelector("#teacher"),student=document.querySelector("#student"),grid=document.querySelector("#student-grid");
let activeFilter="all",stream=null;
function show(view){[entry,teacher,student].forEach(el=>el.hidden=true);view.hidden=false;scrollTo(0,0)}
document.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.role==="teacher"?teacher:student)));
document.querySelectorAll(".exit").forEach(b=>b.addEventListener("click",()=>{if(stream)stream.getTracks().forEach(t=>t.stop());show(entry)}));
function render(){const q=document.querySelector("#student-search").value.trim();const list=students.filter(s=>(activeFilter==="all"||s.status===activeFilter)&&s.name.includes(q));grid.innerHTML=list.map((s,i)=>`<button class="student-card ${s.status}" data-name="${s.name}" data-scene="${s.scene}"><div class="screen scene-${s.scene}"><span class="status">${s.status==="help"?"需要協助":s.status==="waiting"?"尚未分享":s.status==="offline"?"已離線":"分享中"}</span></div><div class="student-info"><span class="avatar">${s.name.slice(-1)}</span><span><b>${s.name}</b><small>${s.group}・${s.updated}</small></span></div></button>`).join("");grid.querySelectorAll(".student-card").forEach(c=>c.addEventListener("click",()=>{document.querySelector("#dialog-name").textContent=c.dataset.name;document.querySelector("#dialog-screen").className=`large-screen scene-${c.dataset.scene}`;document.querySelector("#student-dialog").showModal()}))}
document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter===activeFilter));render()}));
document.querySelector("#student-search").addEventListener("input",render);render();
document.querySelector("#copy-code").addEventListener("click",async e=>{await navigator.clipboard?.writeText(location.origin+"/class/patrol/");e.currentTarget.textContent="已複製";setTimeout(()=>e.currentTarget.textContent="複製連結",1200)});
document.querySelector("#announce").addEventListener("click",()=>document.querySelector("#notice-dialog").showModal());
document.querySelectorAll(".dialog-close").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));
const shareButton=document.querySelector("#share-button"),video=document.querySelector("#share-video");
shareButton.addEventListener("click",async()=>{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;video.hidden=true;shareButton.textContent="開始分享畫面";return}try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:5},audio:false});video.srcObject=stream;video.hidden=false;shareButton.textContent="停止分享";stream.getVideoTracks()[0].addEventListener("ended",()=>{stream=null;video.hidden=true;shareButton.textContent="開始分享畫面"})}catch{}});
document.querySelector("#help-button").addEventListener("click",e=>{e.currentTarget.classList.toggle("active");e.currentTarget.textContent=e.currentTarget.classList.contains("active")?"已通知老師，請稍候":"舉手｜我需要老師協助"});
